# Generated by Django 5.2 on 2025-04-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
